server:
  port: 8082

spring:
  application:
    name: library
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      format_sql: true

jwt:
  expiration: ${JWT_EXPIRATION:900000} #15 minutes
  key: ${JWT_KEY}