server:
  port: 8082

spring:
  application:
    name: library
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/library
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true